pipeline:
  test-vcl:
    image: fpfis/varnish:4.1
    commands:
      - cp -fR ./ /etc/varnish/
      - varnishtest /etc/varnish/test/*.vtc
    environment:
      - VARNISH_PURGE_KEY=aW52YWxpZGF0ZTp0ZXN0

  # build varnish service
  publish-docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: fpfis/varnish-ne:4.1
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push