matrix:
    VARNISH_VERSION:
    - 4.1
    - 6.0

pipeline:
  test-vcl:
    image: fpfis/varnish:${VARNISH_VERSION}
    commands:
      - cp -fR ./ /etc/varnish/
      - varnishtest /etc/varnish/test/*.vtc
    environment:
      - VARNISH_PURGE_KEY=aW52YWxpZGF0ZTp0ZXN0

  # build varnish service
  publish-docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    tags: ${VARNISH_VERSION}
    repo: fpfis/varnish-ne
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push